-- Houzen - PostgreSQL / Supabase
-- MigraÃ§Ã£o idempotente e nÃ£o destrutiva. Execute no SQL Editor do Supabase.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  firebase_uid VARCHAR(128),
  nivel VARCHAR(20) NOT NULL DEFAULT 'operador',
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  status VARCHAR(20) NOT NULL DEFAULT 'ativo',
  permissoes JSONB NOT NULL DEFAULT '["dashboard", "rh", "suprimentos", "frota", "cronograma", "obras"]'::jsonb
);

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS firebase_uid VARCHAR(128);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS temporary_password_expires_at TIMESTAMPTZ;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS session_version INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS usuarios_email_lower_uidx ON usuarios (lower(email));
CREATE UNIQUE INDEX IF NOT EXISTS usuarios_firebase_uid_uidx ON usuarios (firebase_uid) WHERE firebase_uid IS NOT NULL;

CREATE TABLE IF NOT EXISTS obras (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Em Andamento',
  receitas NUMERIC(10,2) NOT NULL DEFAULT 0,
  despesas NUMERIC(10,2) NOT NULL DEFAULT 0,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sedes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS funcionarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  obra_id INTEGER NOT NULL REFERENCES obras(id) ON DELETE CASCADE,
  nome VARCHAR(255) NOT NULL,
  cargo VARCHAR(255) NOT NULL,
  departamento VARCHAR(255) NOT NULL,
  horas VARCHAR(50) DEFAULT '176h',
  salario NUMERIC(10,2) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Ativo'
);

CREATE TABLE IF NOT EXISTS suprimentos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  obra_id INTEGER REFERENCES obras(id) ON DELETE CASCADE,
  sede_id INTEGER REFERENCES sedes(id) ON DELETE CASCADE,
  nome VARCHAR(255) NOT NULL,
  categoria VARCHAR(100) NOT NULL,
  qtd VARCHAR(100) NOT NULL,
  preco NUMERIC(10,2) NOT NULL,
  fornecedor VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'DisponÃ­vel'
);

CREATE TABLE IF NOT EXISTS frota (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  obra_id INTEGER REFERENCES obras(id) ON DELETE CASCADE,
  sede_id INTEGER REFERENCES sedes(id) ON DELETE CASCADE,
  nome VARCHAR(255) NOT NULL,
  tipo VARCHAR(100) NOT NULL,
  codigo VARCHAR(50) NOT NULL,
  operador VARCHAR(255) DEFAULT 'NÃ£o Designado',
  manutencao VARCHAR(100) DEFAULT 'Nenhuma',
  status VARCHAR(50) NOT NULL DEFAULT 'DisponÃ­vel'
);

CREATE TABLE IF NOT EXISTS cronograma (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  obra_id INTEGER NOT NULL REFERENCES obras(id) ON DELETE CASCADE,
  fase VARCHAR(255) NOT NULL,
  descricao TEXT NOT NULL,
  prazo VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Pendente',
  ordem INTEGER NOT NULL DEFAULT 10
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  token_hash CHAR(64) PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS password_reset_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  contact_type VARCHAR(20) NOT NULL CHECK (contact_type IN ('whatsapp', 'email')),
  contact_value VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'rejected')),
  requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ,
  processed_by INTEGER REFERENCES usuarios(id) ON DELETE SET NULL,
  verification_note VARCHAR(500),
  rejection_reason VARCHAR(500)
);

ALTER TABLE password_reset_requests ADD COLUMN IF NOT EXISTS verification_note VARCHAR(500);

-- Tabela legada mantida apenas para compatibilidade com importaÃ§Ãµes antigas.
-- O dashboard atual calcula os totais diretamente das tabelas do usuÃ¡rio.
CREATE TABLE IF NOT EXISTS dashboard_resumo (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  despesas NUMERIC(10,2) NOT NULL,
  receitas NUMERIC(10,2) NOT NULL,
  funcionarios INTEGER NOT NULL,
  equipamentos INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS obras_usuario_id_idx ON obras (usuario_id);
CREATE INDEX IF NOT EXISTS sedes_usuario_id_idx ON sedes (usuario_id);
CREATE INDEX IF NOT EXISTS funcionarios_obra_id_idx ON funcionarios (obra_id);
CREATE INDEX IF NOT EXISTS suprimentos_obra_id_idx ON suprimentos (obra_id) WHERE obra_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS suprimentos_sede_id_idx ON suprimentos (sede_id) WHERE sede_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS frota_obra_id_idx ON frota (obra_id) WHERE obra_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS frota_sede_id_idx ON frota (sede_id) WHERE sede_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS cronograma_obra_ordem_idx ON cronograma (obra_id, ordem);
CREATE INDEX IF NOT EXISTS password_reset_tokens_expires_at_idx ON password_reset_tokens (expires_at);
CREATE INDEX IF NOT EXISTS password_reset_requests_requested_at_idx ON password_reset_requests (requested_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS password_reset_requests_pending_uidx
  ON password_reset_requests (usuario_id) WHERE status = 'pending';

-- Converte senhas em texto simples importadas do dump MySQL para bcrypt.
UPDATE usuarios
SET senha = crypt(senha, gen_salt('bf', 12))
WHERE senha !~ '^\$2[aby]\$[0-9]{2}\$';

DO $$
BEGIN
  ALTER TABLE obras ADD CONSTRAINT obras_valores_nao_negativos CHECK (receitas >= 0 AND despesas >= 0) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE funcionarios ADD CONSTRAINT funcionarios_salario_nao_negativo CHECK (salario >= 0) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE suprimentos ADD CONSTRAINT suprimentos_preco_nao_negativo CHECK (preco >= 0) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE suprimentos ADD CONSTRAINT suprimentos_destino_unico CHECK ((obra_id IS NULL) <> (sede_id IS NULL)) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE frota ADD CONSTRAINT frota_destino_unico CHECK ((obra_id IS NULL) <> (sede_id IS NULL)) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- A aplicaÃ§Ã£o usa conexÃ£o direta apenas no backend. As roles da Data API
-- nÃ£o precisam de acesso Ã s tabelas do domÃ­nio.
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE obras ENABLE ROW LEVEL SECURITY;
ALTER TABLE sedes ENABLE ROW LEVEL SECURITY;
ALTER TABLE funcionarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE suprimentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE frota ENABLE ROW LEVEL SECURITY;
ALTER TABLE cronograma ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE dashboard_resumo ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE usuarios, obras, sedes, funcionarios, suprimentos, frota, cronograma, password_reset_tokens, password_reset_requests, dashboard_resumo FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated;

-- MantÃ©m sequÃªncias/identities alinhadas apÃ³s uma importaÃ§Ã£o com IDs explÃ­citos.
SELECT setval(pg_get_serial_sequence('usuarios', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM usuarios), 1), 1), EXISTS (SELECT 1 FROM usuarios));
SELECT setval(pg_get_serial_sequence('obras', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM obras), 1), 1), EXISTS (SELECT 1 FROM obras));
SELECT setval(pg_get_serial_sequence('sedes', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM sedes), 1), 1), EXISTS (SELECT 1 FROM sedes));
SELECT setval(pg_get_serial_sequence('funcionarios', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM funcionarios), 1), 1), EXISTS (SELECT 1 FROM funcionarios));
SELECT setval(pg_get_serial_sequence('suprimentos', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM suprimentos), 1), 1), EXISTS (SELECT 1 FROM suprimentos));
SELECT setval(pg_get_serial_sequence('frota', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM frota), 1), 1), EXISTS (SELECT 1 FROM frota));
SELECT setval(pg_get_serial_sequence('cronograma', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM cronograma), 1), 1), EXISTS (SELECT 1 FROM cronograma));
SELECT setval(pg_get_serial_sequence('dashboard_resumo', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM dashboard_resumo), 1), 1), EXISTS (SELECT 1 FROM dashboard_resumo));

COMMIT;
